# fly.toml app configuration file generated for gemijs on 2023-11-14T21:41:00+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gemijs"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
