const mode = [
  {
    name: "User",
    dbName: null,
    fields: [
      {
        name: "id",
        kind: "scalar",
        isList: false,
        isRequired: true,
        isUnique: false,
        isId: true,
        isReadOnly: false,
        hasDefaultValue: true,
        type: "String",
        default: { name: "cuid", args: [] },
        isGenerated: false,
        isUpdatedAt: false,
      },
      {
        name: "name",
        kind: "scalar",
        isList: false,
        isRequired: false,
        isUnique: false,
        isId: false,
        isReadOnly: false,
        hasDefaultValue: false,
        type: "String",
        isGenerated: false,
        isUpdatedAt: false,
      },
      {
        name: "email",
        kind: "scalar",
        isList: false,
        isRequired: false,
        isUnique: true,
        isId: false,
        isReadOnly: false,
        hasDefaultValue: false,
        type: "String",
        isGenerated: false,
        isUpdatedAt: false,
      },
      {
        name: "password",
        kind: "scalar",
        isList: false,
        isRequired: false,
        isUnique: false,
        isId: false,
        isReadOnly: false,
        hasDefaultValue: false,
        type: "String",
        isGenerated: false,
        isUpdatedAt: false,
      },
      {
        name: "post",
        kind: "object",
        isList: true,
        isRequired: true,
        isUnique: false,
        isId: false,
        isReadOnly: false,
        hasDefaultValue: false,
        type: "Post",
        relationName: "PostToUser",
        relationFromFields: [],
        relationToFields: [],
        isGenerated: false,
        isUpdatedAt: false,
      },
    ],
    primaryKey: null,
    uniqueFields: [],
    uniqueIndexes: [],
    isGenerated: false,
  },
  {
    name: "Post",
    dbName: null,
    fields: [
      {
        name: "id",
        kind: "scalar",
        isList: false,
        isRequired: true,
        isUnique: false,
        isId: true,
        isReadOnly: false,
        hasDefaultValue: true,
        type: "String",
        default: { name: "cuid", args: [] },
        isGenerated: false,
        isUpdatedAt: false,
      },
      {
        name: "title",
        kind: "scalar",
        isList: false,
        isRequired: true,
        isUnique: false,
        isId: false,
        isReadOnly: false,
        hasDefaultValue: false,
        type: "String",
        isGenerated: false,
        isUpdatedAt: false,
      },
      {
        name: "User",
        kind: "object",
        isList: false,
        isRequired: false,
        isUnique: false,
        isId: false,
        isReadOnly: false,
        hasDefaultValue: false,
        type: "User",
        relationName: "PostToUser",
        relationFromFields: ["userId"],
        relationToFields: ["id"],
        isGenerated: false,
        isUpdatedAt: false,
      },
      {
        name: "userId",
        kind: "scalar",
        isList: false,
        isRequired: false,
        isUnique: false,
        isId: false,
        isReadOnly: true,
        hasDefaultValue: false,
        type: "String",
        isGenerated: false,
        isUpdatedAt: false,
      },
    ],
    primaryKey: null,
    uniqueFields: [],
    uniqueIndexes: [],
    isGenerated: false,
  },
];
